version: '3.4'

services:
  mongo:
    image: mongo:4
    restart: always
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=default
    ports:
      - 27017:27017

  spring:
    build:
      context: .
    restart: always
    depends_on:
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080

volumes:
  mongo:
    name: spring_boot_mongodb