spring:
  data:
    mongodb:
      host: localhost
      database: bookstore
      port: 27017
      username: springboot
      password: springboot

---

spring:
  profiles: prod
  data:
    mongodb:
      host: mongo